apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: dg0401-lifesub-ns
data:
  SERVER_PORT: "8080"
  JPA_DDL_AUTO: "update"
  JPA_SHOW_SQL: "true"
  ALLOWED_ORIGINS: "http://20.214.192.165"
  FEE_LEVEL_COLLECTOR: "50000"
  FEE_LEVEL_ADDICT: "100000"
  JWT_ACCESS_TOKEN_VALIDITY: "3600000"
  JWT_REFRESH_TOKEN_VALIDITY: "86400000"
