apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
  namespace: dg0401-lifesub-ns
data:
  SERVER_PORT: "8081"
  POSTGRES_HOST: "postgres-member-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "member"
