apiVersion: v1
kind: Service
metadata:
  name: recommend-service
  namespace: dg0401-lifesub-ns
  labels:
    app: recommend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: recommend
